env:
  browser: true
  es6: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  "class-methods-use-this": "off",
  "no-param-reassign": "off",
  "import/named": "off",
  "guard-for-in": "off",
  "no-restricted-syntax": "off",
  "consistent-return": "off",
  "linebreak-style": "off",
  "no-underscore-dangle": "off"
}
