language: node_js
node_js: 
      - "stable"
cache:
  directories:
    - "node_modules"

install:
      - npm install
services: 
      -mongodb
env: 
  global:
    - NODE_ENV=test
    - API_SECRET_KEY=df07d49effd0843be8c7ebc4c4dff677261755c118a3d62fef0d2e92ebdc9941
    - MDB_USRNAME-heroku_mgoadmin
    - MDB_PASSWORD-2019!!Heroku

script:
      - npm run test
